name: Deploy Microservice Contas to Azure Container Apps

on:
  push:
    branches:
      - main
    paths:
      - 'microservice-contas/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        working-directory: ./microservice-contas
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/microservice-contas:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/microservice-contas:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: microservice-contas
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/microservice-contas:${{ github.sha }}
